// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddLink(arg1:string):Promise<string>;

export function ClearLinks():Promise<void>;

export function DownloadMP3(arg1:string):Promise<string>;

export function DownloadVideo(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
