// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLink(arg1) {
  return window['go']['backend']['App']['AddLink'](arg1);
}

export function ClearLinks() {
  return window['go']['backend']['App']['ClearLinks']();
}

export function DownloadMP3(arg1) {
  return window['go']['backend']['App']['DownloadMP3'](arg1);
}

export function DownloadVideo(arg1) {
  return window['go']['backend']['App']['DownloadVideo'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
